# Kanvas is a distributed system with multiple databases, servers, and web browser clients
# For development, we can spin everything up via docker-compose


services:
  store-db:
    image: postgres:13
    command:
      - postgres
      - -c
      - wal_level=logical  # <- required for logical replication
    ports:
      - 54320:5432
    environment:
      POSTGRES_USER: store_pguser
      POSTGRES_PASSWORD: store_pgpass
      POSTGRES_DB: dev_database

  store-api:
    build:
      context: .
      dockerfile: ./store-api-server/Dockerfile
    entrypoint: |-
      bash -c '
        set -e
        ./script/wait-db
        INIT_QUEPASA=false ./script/migrate up
        if [[ "`psql -c \"select count(1) from kanvas_user\" -tA`" == "0" ]]; then
          if [ -v DEPLOYMENT ]; then
            psql < script/populate-stagingdb.sql
          else
            psql < script/populate-testdb.sql
          fi
        fi
        if [ "${STORE_API_ENABLED:-true}" != "false" ]; then
          yarn start
        fi
      '
    ports:
      - 3005:3000
    links:
      - store-db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - store-api-server/.env
    environment:
      PGHOST: store-db
      PGPORT: 5432
      PGUSER: store_pguser
      PGPASSWORD: store_pgpass
      PGDATABASE: dev_database

      KANVAS_API_PORT: 3000


  store-quepasa:
    image: ghcr.io/tzconnectberlin/que-pasa:1.2.0
    entrypoint: |-
      bash -c '
        set -e -x
        while ! psql -d "$$DATABASE_URL" -c "select 1" ; do
          sleep 1
        done
        /que-pasa/que-pasa --bcd-enable
      '
    volumes:
      - ./config:/config
    environment:
      PGHOST: store-db
      PGPORT: 5432
      PGUSER: store_pguser
      PGPASSWORD: store_pgpass
      PGDATABASE: dev_database
      DATABASE_URL: "postgres://store_pguser:store_pgpass@store-db:5432/dev_database"
      CONTRACT_SETTINGS: /config/kanvas.yaml
      NODE_URL: https://ithaca-archive.tzconnect.berlin
      BCD_NETWORK: ithacanet


  admin-db:
    image: postgres:13
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: admin_pguser
      POSTGRES_PASSWORD: admin_pgpass
      POSTGRES_DB: dev_database

  admin-api:
    build:
      context: .
      dockerfile: ./admin-api-server/Dockerfile
    entrypoint: |-
      bash -c '
        set -e
        ./script/wait-db
        INIT_QUEPASA=false ./script/migrate
        if [[ "`psql -c \"select count(1) from kanvas_user\" -tA`" == "0" ]]; then
          yarn seed
          ./script/setup-replication-sub
        fi
        if [ "${ADMIN_API_ENABLED:-true}" != "false" ]; then
          yarn run start
        fi
      '
    ports:
      - 3006:3001
    links:
      - admin-db
      - store-db
      - store-api
    env_file:
      - admin-api-server/.env
    environment:
      POSTGRES_USER: admin_pguser
      POSTGRES_PASSWORD: admin_pgpass
      POSTGRES_DB: dev_database

      PGHOST: admin-db
      PGPORT: 5432
      PGUSER: admin_pguser
      PGPASSWORD: admin_pgpass
      PGDATABASE: dev_database

      STORE_PGHOST: store-db
      STORE_PGPORT: 5432
      STORE_PGUSER: store_pguser
      STORE_PGPASSWORD: store_pgpass
      STORE_PGDATABASE: dev_database

      ADMIN_API_PORT: 3001
      STORE_API: http://store-api:3000


  admin-quepasa:
    image: ghcr.io/tzconnectberlin/que-pasa:1.2.0
    entrypoint: |-
      bash -c '
        set -e
        while ! psql -d "$$DATABASE_URL" -c "select 1" ; do
          sleep 1
        done
        /que-pasa/que-pasa --bcd-enable
      '
    volumes:
      - ./config:/config
    environment:
      PGHOST: admin-db
      PGPORT: 5432
      PGUSER: admin_pguser
      PGPASSWORD: admin_pgpass
      PGDATABASE: store_replication
      DATABASE_URL: "postgres://admin_pguser:admin_pgpass@admin-db:5432/store_replication"
      CONTRACT_SETTINGS: /config/kanvas.yaml
      NODE_URL: https://ithaca-archive.tzconnect.berlin
      BCD_NETWORK: ithacanet
